/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface PublicRoom {
  tiles: PublicTile[];
  [k: string]: unknown;
}
export interface PublicTile {
  name: string;
  wall: boolean;
  x: number;
  y: number;
  [k: string]: unknown;
}
export interface PublicWorld {
  rooms: PublicRoomManifest[];
  [k: string]: unknown;
}
export interface PublicRoomManifest {
  name: string;
  screen_space_x: number;
  screen_space_y: number;
  [k: string]: unknown;
}
