/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PubEntityType = "Crab";

export interface PubRoom {
  entities: PubEntity[];
  tiles: PublicTile[];
  [k: string]: unknown;
}
export interface PubEntity {
  id: number;
  pos: PubCord;
  ty: PubEntityType;
  [k: string]: unknown;
}
export interface PubCord {
  q: number;
  r: number;
  s: number;
  [k: string]: unknown;
}
export interface PublicTile {
  cord: PubCord;
  name: string;
  wall: boolean;
  [k: string]: unknown;
}
export interface WorldManifest {
  rooms: RoomManifest[];
  [k: string]: unknown;
}
export interface RoomManifest {
  name: string;
  screen_space_x: number;
  screen_space_y: number;
  [k: string]: unknown;
}
